export type EditorOption = { value: string; label: string };

export type EditorField = {
  name: string;
  label: string;
  kind: "text" | "textarea" | "number" | "checkbox" | "select" | "image" | "list" | "date" | "url" | "email" | "product-picker";
  helper?: string;
  placeholder?: string;
  options?: EditorOption[] | "categories";
  fullWidth?: boolean;
  step?: number;
  min?: number;
  max?: number;
  optional?: boolean;
};

export const collectionConfigs = {
  products: {
    title: "Products",
    singular: "product",
    description: "Control what guests see on the live CHOP menu, including price, availability, and featured placement.",
    nameField: "name",
    imageField: "img",
    secondaryField: "category",
    defaults: {
      name: "",
      desc: "",
      category: "",
      price: 0,
      oldPrice: null,
      img: "",
      additionalImages: [],
      available: true,
      featured: false,
      popular: false,
      isNew: false,
      sortOrder: 0,
      tags: [],
      ingredients: "",
      size: "",
      preparation: "",
    },
    fields: [
      { name: "name", label: "Product name", kind: "text", fullWidth: true, placeholder: "e.g. Waakye" },
      { name: "category", label: "Category", kind: "select", options: "categories" },
      { name: "price", label: "Price (GH₵)", kind: "number", min: 0.01, step: 0.01 },
      { name: "oldPrice", label: "Previous price (GH₵)", kind: "number", min: 0, step: 0.01, optional: true, helper: "Leave blank when there is no discount." },
      { name: "img", label: "Main image", kind: "image", fullWidth: true, helper: "Upload a new image or choose one from the media library." },
      { name: "additionalImages", label: "Additional images", kind: "list", fullWidth: true, helper: "Add one image URL per line." },
      { name: "desc", label: "Description", kind: "textarea", fullWidth: true },
      { name: "available", label: "Available to order", kind: "checkbox", helper: "Turn off when the item is temporarily unavailable." },
      { name: "featured", label: "Featured on the homepage", kind: "checkbox" },
      { name: "popular", label: "Popular item", kind: "checkbox" },
      { name: "isNew", label: "Mark as new", kind: "checkbox" },
      { name: "sortOrder", label: "Menu position", kind: "number", min: 0, step: 1 },
      { name: "tags", label: "Tags", kind: "list", fullWidth: true, helper: "One tag per line." },
      { name: "ingredients", label: "Ingredients", kind: "textarea", fullWidth: true },
      { name: "size", label: "Size or variant", kind: "text" },
      { name: "preparation", label: "Preparation information", kind: "text" },
    ] satisfies EditorField[],
  },
  categories: {
    title: "Categories",
    singular: "category",
    description: "Create, order, describe, publish, or hide menu categories. Products keep their category when its name changes.",
    nameField: "name",
    imageField: "image",
    secondaryField: "slug",
    defaults: { name: "", slug: "", description: "", image: "", icon: "fas fa-utensils", sortOrder: 0 },
    fields: [
      { name: "name", label: "Category name", kind: "text", fullWidth: true },
      { name: "slug", label: "URL identifier", kind: "text", helper: "Generated from the name when left blank. Existing identifiers stay fixed after creation." },
      { name: "sortOrder", label: "Display position", kind: "number", min: 0, step: 1 },
      { name: "description", label: "Description", kind: "textarea", fullWidth: true },
      { name: "image", label: "Category image", kind: "image", fullWidth: true },
      { name: "icon", label: "Icon class", kind: "text", helper: "Font Awesome class, for example fas fa-utensils." },
    ] satisfies EditorField[],
  },
  promotions: {
    title: "Promotions",
    singular: "promotion",
    description: "Manage offer cards, discount prices, visibility dates, and the live deals section.",
    nameField: "name",
    imageField: "img",
    secondaryField: "badge",
    defaults: { name: "", slug: "", desc: "", price: 0, originalPrice: null, badge: "", img: "", startDate: "", endDate: "", ctaText: "", ctaHref: "#menu", sortOrder: 0 },
    fields: [
      { name: "name", label: "Promotion name", kind: "text", fullWidth: true },
      { name: "price", label: "Offer price (GH₵)", kind: "number", min: 0.01, step: 0.01 },
      { name: "originalPrice", label: "Original price (GH₵)", kind: "number", min: 0, step: 0.01, optional: true },
      { name: "badge", label: "Offer badge", kind: "text", placeholder: "20% OFF" },
      { name: "sortOrder", label: "Display position", kind: "number", min: 0, step: 1 },
      { name: "img", label: "Promotion image", kind: "image", fullWidth: true },
      { name: "desc", label: "Description", kind: "textarea", fullWidth: true },
      { name: "startDate", label: "Starts on", kind: "date" },
      { name: "endDate", label: "Ends on", kind: "date" },
      { name: "ctaText", label: "Button text", kind: "text" },
      { name: "ctaHref", label: "Button destination", kind: "url" },
    ] satisfies EditorField[],
  },
  announcements: {
    title: "Announcements",
    singular: "announcement",
    description: "Publish timed notices in the storefront promo strip. Drafts and hidden notices stay off the public website.",
    nameField: "title",
    imageField: "image",
    secondaryField: "message",
    defaults: { title: "", message: "", image: "", link: "", startDate: "", endDate: "", sortOrder: 0 },
    fields: [
      { name: "title", label: "Announcement title", kind: "text", fullWidth: true },
      { name: "message", label: "Announcement message", kind: "textarea", fullWidth: true },
      { name: "image", label: "Image", kind: "image", fullWidth: true },
      { name: "link", label: "Link destination", kind: "url" },
      { name: "sortOrder", label: "Display position", kind: "number", min: 0, step: 1 },
      { name: "startDate", label: "Starts on", kind: "date" },
      { name: "endDate", label: "Ends on", kind: "date" },
    ] satisfies EditorField[],
  },
  delivery: {
    title: "Delivery areas",
    singular: "delivery area",
    description: "Add service areas, local fees, minimums, estimated delivery time, and availability.",
    nameField: "name",
    imageField: "",
    secondaryField: "city",
    defaults: { name: "", city: "", fee: 5, minimumOrder: 0, deliveryTime: "30–45 minutes", instructions: "", available: true, sortOrder: 0 },
    fields: [
      { name: "name", label: "Area display name", kind: "text" },
      { name: "city", label: "Checkout area value", kind: "text", helper: "Must match the area selected by a customer at checkout." },
      { name: "fee", label: "Delivery fee (GH₵)", kind: "number", min: 0, step: 0.01 },
      { name: "minimumOrder", label: "Minimum order (GH₵)", kind: "number", min: 0, step: 0.01 },
      { name: "deliveryTime", label: "Estimated delivery", kind: "text" },
      { name: "sortOrder", label: "Display position", kind: "number", min: 0, step: 1 },
      { name: "available", label: "Available for delivery", kind: "checkbox" },
      { name: "instructions", label: "Delivery instructions", kind: "textarea", fullWidth: true },
    ] satisfies EditorField[],
  },
  navigation: {
    title: "Navigation links",
    singular: "navigation link",
    description: "Edit the public header and footer links. The CMS route itself is never included in this list.",
    nameField: "label",
    imageField: "",
    secondaryField: "url",
    defaults: { label: "", url: "#menu", section: "header", visible: true, sortOrder: 0 },
    fields: [
      { name: "label", label: "Link label", kind: "text" },
      { name: "url", label: "Destination", kind: "url", helper: "Use a section anchor or safe https, phone, or email link." },
      { name: "section", label: "Show in", kind: "select", options: [{ value: "header", label: "Header navigation" }, { value: "footer", label: "Footer links" }] },
      { name: "sortOrder", label: "Display position", kind: "number", min: 0, step: 1 },
      { name: "visible", label: "Show this link", kind: "checkbox" },
    ] satisfies EditorField[],
  },
} as const;

export const contentEditorConfigs = {
  "site-settings": {
    title: "Website content & settings",
    description: "Update CHOP's contact details, location, hours, social accounts, currency, and search metadata.",
    defaults: {
      businessName: "Chop", tagline: "Taste the Vibe", phone: "", whatsapp: "", email: "", address: "", locationUrl: "", openingHours: "", instagram: "", facebook: "", tiktok: "", twitter: "", defaultSeoTitle: "", metaDescription: "", socialImage: "/chop.png", currency: "GHS", websiteStatus: "open", footerText: "",
    },
    fields: [
      { name: "businessName", label: "Business name", kind: "text" },
      { name: "tagline", label: "Tagline", kind: "text" },
      { name: "phone", label: "Phone number", kind: "text" },
      { name: "whatsapp", label: "WhatsApp number", kind: "text" },
      { name: "email", label: "Business email", kind: "email" },
      { name: "address", label: "Location / address", kind: "text" },
      { name: "locationUrl", label: "Google Maps link", kind: "url" },
      { name: "openingHours", label: "Opening hours", kind: "textarea", fullWidth: true },
      { name: "instagram", label: "Instagram", kind: "url" },
      { name: "facebook", label: "Facebook", kind: "url" },
      { name: "tiktok", label: "TikTok", kind: "url" },
      { name: "twitter", label: "X / Twitter", kind: "url" },
      { name: "defaultSeoTitle", label: "Default SEO title", kind: "text", fullWidth: true },
      { name: "metaDescription", label: "Meta description", kind: "textarea", fullWidth: true },
      { name: "socialImage", label: "Social sharing image", kind: "image", fullWidth: true },
      { name: "currency", label: "Currency", kind: "select", options: [{ value: "GHS", label: "Ghana cedi (GHS)" }, { value: "USD", label: "US dollar (USD)" }, { value: "GBP", label: "Pound sterling (GBP)" }, { value: "EUR", label: "Euro (EUR)" }] },
      { name: "websiteStatus", label: "Website status", kind: "select", options: [{ value: "open", label: "Open" }, { value: "closed", label: "Closed" }, { value: "maintenance", label: "Maintenance" }] },
      { name: "footerText", label: "Footer text", kind: "text", fullWidth: true },
    ] satisfies EditorField[],
  },
  homepage: {
    title: "Homepage",
    description: "Edit the hero, featured selections, and promotional section. Save a draft, preview it, then publish when ready.",
    defaults: {
      heroTitle: "Taste the Vibe", heroSubtitle: "Bold. Fresh. Unmatched.", heroDescription: "", heroImage: "", heroCtaText: "Explore Menu", heroCtaLink: "#menu", promoHeading: "Today's Special Offers", promoText: "", promoImage: "", promoBadge: "Hot Deals", promoButtonText: "View Deals", promoButtonLink: "#deals", promoStart: "", promoEnd: "", showHero: true, showPromo: true, featuredProductIds: [], popularProductIds: [],
    },
    fields: [
      { name: "showHero", label: "Show hero section", kind: "checkbox" },
      { name: "heroTitle", label: "Hero heading", kind: "text" },
      { name: "heroSubtitle", label: "Hero subheading", kind: "text" },
      { name: "heroDescription", label: "Hero description", kind: "textarea", fullWidth: true },
      { name: "heroImage", label: "Hero image", kind: "image", fullWidth: true },
      { name: "heroCtaText", label: "Primary button text", kind: "text" },
      { name: "heroCtaLink", label: "Primary button link", kind: "url" },
      { name: "featuredProductIds", label: "Featured products", kind: "product-picker", fullWidth: true },
      { name: "popularProductIds", label: "Popular products", kind: "product-picker", fullWidth: true },
      { name: "showPromo", label: "Show promotion section", kind: "checkbox" },
      { name: "promoHeading", label: "Promotion heading", kind: "text" },
      { name: "promoBadge", label: "Promotion label", kind: "text" },
      { name: "promoText", label: "Promotion copy", kind: "textarea", fullWidth: true },
      { name: "promoImage", label: "Promotion image", kind: "image", fullWidth: true },
      { name: "promoButtonText", label: "Promotion button text", kind: "text" },
      { name: "promoButtonLink", label: "Promotion button link", kind: "url" },
      { name: "promoStart", label: "Promotion starts", kind: "date" },
      { name: "promoEnd", label: "Promotion ends", kind: "date" },
    ] satisfies EditorField[],
  },
  about: {
    title: "About CHOP",
    description: "Keep the public story current with CHOP's history, mission, values, and brand imagery.",
    defaults: { title: "We Don't Just Cook. We Vibe.", description: "", story: "", mission: "", vision: "", values: "", image: "", visible: true },
    fields: [
      { name: "visible", label: "Show the About section", kind: "checkbox" },
      { name: "title", label: "About title", kind: "text", fullWidth: true },
      { name: "description", label: "About description", kind: "textarea", fullWidth: true },
      { name: "story", label: "Business story", kind: "textarea", fullWidth: true },
      { name: "mission", label: "Mission", kind: "textarea" },
      { name: "vision", label: "Vision", kind: "textarea" },
      { name: "values", label: "Values", kind: "textarea", helper: "One value per line." },
      { name: "image", label: "About image", kind: "image", fullWidth: true },
    ] satisfies EditorField[],
  },
  "delivery-settings": {
    title: "Delivery settings",
    description: "Set the delivery fee, free-delivery threshold, minimum basket, and customer instructions.",
    defaults: { defaultFee: 5, freeDeliveryThreshold: 100, minimumOrder: 0, estimatedTime: "30–45 minutes", deliveryAvailable: true, instructions: "", pickupInfo: "" },
    fields: [
      { name: "deliveryAvailable", label: "Accept delivery orders", kind: "checkbox" },
      { name: "defaultFee", label: "Default fee (GH₵)", kind: "number", min: 0, step: 0.01 },
      { name: "freeDeliveryThreshold", label: "Free delivery from (GH₵)", kind: "number", min: 0, step: 0.01 },
      { name: "minimumOrder", label: "Minimum order (GH₵)", kind: "number", min: 0, step: 0.01 },
      { name: "estimatedTime", label: "Estimated delivery time", kind: "text" },
      { name: "instructions", label: "Delivery instructions", kind: "textarea", fullWidth: true },
      { name: "pickupInfo", label: "Pickup information", kind: "textarea", fullWidth: true },
    ] satisfies EditorField[],
  },
  "footer-settings": {
    title: "Footer content",
    description: "Manage the footer logo, business description, opening hours, contact display, and copyright.",
    defaults: { logo: "/choplifelogo1.png", businessDescription: "", location: "Elmina, Ghana", openingHours: "", announcement: "", copyright: "", showLogo: true, showContactDetails: true },
    fields: [
      { name: "showLogo", label: "Show the brand logo", kind: "checkbox" },
      { name: "showContactDetails", label: "Show footer contact details", kind: "checkbox" },
      { name: "logo", label: "Footer logo", kind: "image", fullWidth: true },
      { name: "businessDescription", label: "Footer description", kind: "textarea", fullWidth: true },
      { name: "location", label: "Location", kind: "text" },
      { name: "openingHours", label: "Opening hours", kind: "textarea" },
      { name: "announcement", label: "Footer announcement", kind: "text", fullWidth: true },
      { name: "copyright", label: "Copyright text", kind: "text", fullWidth: true },
    ] satisfies EditorField[],
  },
  "promo-messages": {
    title: "Promo strip messages",
    description: "Edit the rotating short messages displayed above the menu.",
    defaults: { messages: [] },
    fields: [
      { name: "messages", label: "Messages", kind: "list", fullWidth: true, helper: "One message per line. Up to 20 messages." },
    ] satisfies EditorField[],
  },
} as const;
